config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad unless ARGV.grep(/assets:precompile/).any?
  get 'european_tours/index'
  get 'ukrainian_tours/index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  resources :contacts, only: [:new, :create]
  get 'contact' => 'contacts#new'

  resources :users
  resources :sessions, except: [:edit, :update] do
    collection do
      get :destroy_admin_user
    end
  end
  resources :european_tours
  resources :ukrainian_tours
  resources :tours
  resources :places
  root 'tours#index'
end

app/controllers/ukrainian_tours_controller.rb
class UkrainianToursController < ApplicationController
  def index
    @pagy, @tours = pagy(Tour.by_ukrainian_tours
      .by_duration(search_params[:duration])
      .by_title(search_params[:title])
      .by_price(search_params[:min_price], search_params[:max_price]), items: 4)

    @tours_all = Tour.by_ukrainian_tours
  end

  private
  def search_params
    params.permit(:duration, :title, :min_price, :max_price)
  end
end

app/helpers/ukrainian_tours_helper.rb
module UkrainianToursHelper
end

app/views/ukrainian_tours/index.html.erb
<% if @tours.count > 2 %>
  <div class="flexslider">
    <ul class="slides">
      <% @tours[0..2].each do |tour| %>
        <li>
          <%= image_tag(tour.image.url, alt: 'Tour image') if tour.image? %>
          <div class="container">
            <div class="flex-caption">
              <h2><%= link_to tour.title, tour_path(tour.id) if tour.title? %></h2>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="filters-block">
  <div class="container">
    <%= form_with url: ukrainian_tours_path, method: :get, data: { remote: false } do |f| %>
      <%= f.select :duration, options_for_select(Tour::DURATION, params[:duration]), { include_blank: 'Направление' }, class: 'duration-select' %>
      <%= f.text_field :title, placeholder: 'Искать в названии тура', value: params[:title], class: 'title-input' %>
      <%= f.text_field :min_price, placeholder: 'Цена от', value: params[:min_price], class: 'price-input' %>
      <%= f.text_field :max_price, placeholder: 'Цена до', value: params[:max_price], class: 'price-input' %>
      <span class="fa fa-search"><%= f.submit "", class: 'search-button' %></span>
    <% end %>
  </div>
</div>

<div class="tours-wrapper">
  <div class="container">
    <ul class="row tours-list">
      <% @tours.each do |tour| %>
        <li class="col-md-6">
          <div class="tours-item">
            <%= image_tag(tour.image.url, alt: 'Tour image', class: "img-responsive" ) if tour.image? %>
            <h2><%= link_to tour.title, tour_path(tour) if tour.title? %></h2>
            <span><%= tour.price %>грн</span>
          </div>
        </li>
      <% end %>
    </ul>
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>
</div>