config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad unless ARGV.grep(/assets:precompile/).any?
  get 'european_tours/index'
  get 'ukrainian_tours/index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  resources :contacts, only: [:new, :create]
  get 'contact' => 'contacts#new'

  resources :users
  resources :sessions, except: [:edit, :update] do
    collection do
      get :destroy_admin_user
    end
  end
  resources :european_tours
  resources :ukrainian_tours
  resources :tours
  resources :places
  root 'tours#index'
end

app/models/tour.rb
class Tour < ApplicationRecord
  require 'carrierwave'
  require 'carrierwave/orm/activerecord'
  mount_uploader :image, ImageUploader

  validates :title, :presence => true
  validates :category, :presence => true

  DURATION = Tour.pluck(:duration).uniq.sort

  scope :by_duration, -> (duration) do
    where(duration: duration) if duration.present?
  end

  scope :by_title, -> (title) do
    where("title LIKE ?", "%#{title}%") if title.present?
  end

  scope :by_price, -> (min_price, max_price) do
    where( price: min_price..max_price ) if min_price.present? && max_price.present?
  end

  scope :by_ukrainian_tours, -> do
    where(category: "Туры по Украине")
  end

  scope :by_european_tours, -> do
    where(category: "Туры по Европе")
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @pagy, @tours = pagy(Tour
                .by_duration(search_params[:duration])
                .by_title(search_params[:title])
                .by_price(search_params[:min_price], search_params[:max_price]), items: 4)
    @tours_all = Tour.all
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def new
    @tour = Tour.new
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      redirect_to tours_path
    else
      render 'new'
    end
  end

  def update
    @tour = Tour.find(params[:id])
    if @tour.update_attributes(tour_params)
      redirect_to tour_path(@tour)
    else
      render 'edit'
    end
  end

  def destroy
    tour = Tour.find(params[:id])
    tour.destroy

    redirect_to tours_path
  end

  private
  def search_params
    params.permit(:duration, :title, :min_price, :max_price)
  end

  def tour_params
    params.require(:tour).permit(:title, :image, :price, :category, :description, :program, :city, :date, :duration)
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= #form_for tour do |f| %>
  <!--<div>
    <%#= f.label :image %>
    <%#= f.file_field :image %>
  </div>

  <div>
    <%#= f.label :title %>
    <%#= f.text_field :title %>
  </div>

  <div>
    <%#= f.label :category %>
    <%#= f.text_field :category %>
  </div>

  <div>
    <%#= f.label :price %>
    <%#= f.text_field :price %>
  </div>

  <div>
    <%#= f.label :city %>
    <%#= f.text_field :city %>
  </div>

  <div>
    <%#= f.label :date %>
    <%#= f.text_field :date %>
  </div>

  <div>
    <%#= f.label :duration %>
    <%#= f.text_field :duration %>
  </div>


  <div>
    <%#= f.label :description %>
    <%#= f.text_area :description, class: "wysiwyg" %>
  </div>


  <div>
    <%#= f.label :program %>
    <%#= f.text_area :program, class: "wysiwyg" %>
  </div>

  <%#= f.submit %>-->
<%# end %>

<script>
    $(function() {
        $('.wysiwyg').froalaEditor();
    });
</script>

app/views/tours/_navbar.html.erb
<header class="header-block">
  <div class="container">
    <ul class="navbar-list">
      <li><%= link_to image_tag("logo.png", alt: "Logo", class: 'logo'), root_path %></li>
      <li><%= link_to "Туры по Украине", ukrainian_tours_path %></li>
      <li><%= link_to "Туры по Европе", european_tours_path %></li>
      <li><%= link_to "Интересные места", places_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
    </ul>
  </div>
</header>

app/views/tours/edit.html.erb
<!--<h1>Edit tour</h1>

<%#= render 'form', tour: @tour %>

<%#= link_to 'Back', tours_path %>-->

app/views/tours/index.html.erb
<% if @tours_all.count > 2 %>
  <div class="flexslider">
    <ul class="slides">
      <% @tours_all[0..2].each do |tour| %>
        <li>
          <%= image_tag(tour.image.url, alt: 'Tour image') if tour.image? %>
          <div class="container">
            <div class="flex-caption">
              <h2><%= link_to tour.title, tour_path(tour.id) if tour.title? %></h2>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="filters-block">
  <div class="container">
    <%= form_with url: tours_path, method: :get, data: { remote: false } do |f| %>
      <%= f.select :duration, options_for_select(Tour::DURATION, params[:duration]), { include_blank: 'Направление' }, class: 'duration-select' %>
      <%= f.text_field :title, placeholder: 'Искать в названии тура', value: params[:title], class: 'title-input' %>
      <%= f.text_field :min_price, placeholder: 'Цена от', value: params[:min_price], class: 'price-input' %>
      <%= f.text_field :max_price, placeholder: 'Цена до', value: params[:max_price], class: 'price-input' %>
      <span class="fa fa-search"><%= f.submit "", class: 'search-button' %></span>
    <% end %>
  </div>
</div>

<div class="tours-wrapper">
  <div class="container">
    <ul class="row tours-list">
      <% @tours.each do |tour| %>
        <li class="col-md-6">
          <div class="tours-item">
            <%= image_tag(tour.image.url, alt: 'Tour image', class: "img-responsive" ) if tour.image? %>
            <h2><%= link_to tour.title, tour_path(tour), class: "title" if tour.title? %></h2>
            <span><%= tour.price %>грн</span>
          </div>
        </li>
      <% end %>
    </ul>
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>
</div>

app/views/tours/new.html.erb
<!--<h1>Add tour</h1>

<%#= render 'form', tour: @tour %>-->

<%#= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<div class="header-banner">
  <%= image_tag(@tour.image.url, alt: 'Image') if @tour.image? %>
  <div class="container">
    <h1><%= @tour.title %></h1>
    <p><%= 5.times.map{ content_tag(:span, "", class: "fa fa-star") }.reduce(&:+) %></p>
  </div>
</div>

<div class="tabs-section">
  <div class="tabs-names-block">
    <ul class="container names-list">
      <li class="active-tab">Описание</li>
      <li>Программа</li>
    </ul>
  </div>

  <div class="tabs-descriptions-block">
    <ul class="container descriptions-list">
      <li class="tab-content active-tab-content">
        <ul class="description-info">
          <li><span class="fa fa-flag"></span><%= @tour.category %></li>
          <li><span class="fa fa-map-marker"></span><%= @tour.city %></li>
          <li><span class="fa fa-globe"></span><%= @tour.duration %></li>
          <li><span class="fa fa-clock-o"></span><%= @tour.date %></li>

        </ul>
        <p class="price">Цена:
          <%= @tour.price %>
          <% if @tour.category == "Туры по Европе" %>
            €
          <% else %>
            грн
          <% end %>
        </p>
        <div><%= raw(@tour.description) %></div>
      </li>
      <li class="tab-content">
        <div><%= raw(@tour.program) %></div>
      </li>
    </ul>
  </div>
</div>